services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8090
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "8080", "--https-port", "8443"]
    ports:
      - "8090:8080"
      - "8443:8443"
    networks:
      - library-network

  user-service:
    build:
      context: .
      dockerfile: ./microservicio-usuarios/Dockerfile
    container_name: library-user-service
    ports:
      - '8081:8081'
    networks:
      - library-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8081/actuator/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  catalog-service:
    build:
      context: .
      dockerfile: ./microservicio-catalogo/Dockerfile
    container_name: library-catalog-service
    ports:
      - '8082:8082'
    networks:
      - library-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8082/actuator/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  notification-service:
    build:
      context: .
      dockerfile: ./microservicio-notificacion/Dockerfile
    container_name: library-notification-service
    ports:
      - '8084:8084'
    networks:
      - library-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8084/actuator/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  circulation-service:
    build:
      context: .
      dockerfile: ./microservicio-circulacion/Dockerfile
    container_name: library-circulation-service
    ports:
      - '8083:8083'
    networks:
      - library-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8083/actuator/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  library-network:
    driver: bridge
    name: library-microservices-network
